# Bybit first-party application and API domains
.byabcde.com
.byapis.com
.byapps.net
.bybdc6.com
.bybit-aws.com
.bybit-global.com
.bybit.biz
.bybit.cloud
.bybit.com
.bybitglobal.com
.bycbe.com
.bycsi.com
.byd3c3.com
.bymj.io
.bytick.com
