# Centralized cryptocurrency exchanges
.binance.com
.bitget.com
.cbhq.net
.coinbase.com
.coinbasecdn.net
.crypto.com
.gemini.com
.kraken.com
.kraken.tech
.krakenassets.com
.kucoin.com
.mexc.com
.okx.com

# Binance additional first-party infrastructure
.binance.co
.binance.cloud
.binance.info
.binance.me
.binance.net
.binanceapi.com
.bnbstatic.com
.bntrace.com
.bsappapi.cc
.bsappapi.com
.bscdnweb.com

# Bitget
.bitgetapp.com

# Bybit
.bybit.com
.bybit.biz
.bytick.com
.bycsi.com
.byapis.com
.bycbe.com
.bymj.io
.byabcde.com
.byapps.net
.byd3c3.com
.bybdc6.com
.bybit-global.com
.bybit.cloud
.bybitglobal.com
.bybit-aws.com

# Gate
.gate.com
.gate.io
.gateio.ws
.gatedata.org
.gateimg.com
.gateio.live
.gateio.services

# HTX / Huobi
.htx.com
.hbabit.com
.hbfile.net
.huobi.com
.huobi.me
.huobi.pro
.huobi.sc
.huobiasia.vip
.huobigroup.com
.huobitoken.com

# Kraken
.kraken.onl

# KuCoin
.kucoin.plus

# MEXC
.mexc.co
.mexc.fm
.mexcsensors.com

# OKX
.okex.com
.okx-dns.com
.okx-dns1.com
.okx-dns2.com
.okx.ac
.okx.cab
