# Centralized cryptocurrency exchanges
.binance.com
.bitget.com
.cbhq.net
.coinbase.com
.coinbasecdn.net
.crypto.com
.gemini.com
.kraken.com
.kraken.tech
.krakenassets.com
.kucoin.com
.mexc.com
.okx.com
