# Mainland China banks and UnionPay
.95516.com
.abcchina.com
.abcchina.com.cn
.abchina.com
.bankcomm.com
.bankofbeijing.com.cn
.bankofchina.com
.bankofshanghai.com
.boc.cn
.ccb.com
.ccb.com.cn
.cebbank.com
.cgbchina.com.cn
.cib.com.cn
.citicbank.com
.cmbc.com.cn
.cmbchina.com
.hxb.com.cn
.icbc.com.cn
.pingan.com
.psbc.com
.spdb.com.cn
.unionpay.com
