# Cross-region financial institutions and first-party financial services

.aexp.com
.afterpay.com
.americanexpress.com
.amex.com
.antbank.com
.bankofchina.com
.bmo.com
.citi.com
.citibank.com
.futunn.com
.hsbc.com
.ibkr.com
.interactivebrokers.com
.klarna.com
.moneygram.com
.moomoo.com
.payoneer.com
.remitly.com
.revolut.com
.sc.com
.sezzle.com
.skrill.com
.webull.com
.welab.co
.westernunion.com
.wise.com
.zip.co

# Longbridge shared platform and infrastructure

.longbridge.cloud
.longbridge.cn
.longbridge.com
.longbridge.global
.longbridgeapp.com
.longportapp.com
.lbctrl.com
.lbkrs.com
.wbrks.com
