# Cross-region financial institutions and first-party financial services

.aexp.com
.afterpay.com
.americanexpress.com
.amex.com
.antbank.com
.bmo.com
.citi.com
.citibank.com
.futunn.com
.hsbc.com
.ibkr.com
.interactivebrokers.com
.klarna.com
.moneygram.com
.moomoo.com
.payoneer.com
.remitly.com
.revolut.com
.sc.com
.sezzle.com
.skrill.com
.webull.com
.welab.co
.westernunion.com
.wise.com
.zip.co

# Financial account linking and data aggregation

.akoya.com
.argyle.com
.finicity.com
.mx.com
.plaid.com
.plaidcdn.com
.yodlee.com

# KYC and identity verification

.socure.com
.socure.co
.withpersona.com
.persona.com
.jumio.com
.netverify.com
.onfido.com
.trulioo.com
.idology.com
.au10tix.com
.alloy.com
.sentilink.com
.middesk.com
.prove.com
.proveidentity.com
.miteksystems.com
.mitekcloud.com
.veriff.com
.sumsub.com
.vouched.id
.ekata.com

# Finance-focused fraud and behavioral verification

.sardine.ai
.biocatch.com
