# Japan financial services
.aeonbank.co.jp
.jibunbank.co.jp
.jp-bank.japanpost.jp
.mizuhobank.co.jp
.mufg.jp
.netbk.co.jp
.paypay-bank.co.jp
.rakuten-bank.co.jp
.resonabank.co.jp
.sbishinseibank.co.jp
.smbc.co.jp
.smbctb.co.jp
.sonybank.net
.sevenbank.co.jp

# Interactive Brokers Japan

.interactivebrokers.co.jp
