# Shared device fingerprinting and fraud prevention services
.sardine.ai
.sift.com
.siftcdn.net
.online-metrix.net
.threatmetrix.com
.iovation.com
.iovation.io
.biocatch.com
.fingerprint.com
.fingerprintjs.com
.riskified.com
.forter.com
.castle.io
.seon.io
.incognia.com
