# Singapore financial services
.bankofsingapore.com
.citibank.com.sg
.dbs.com.sg
.dtcpay.com
.endowus.com
.gxs.com.sg
.hsbc.com.sg
.maribank.sg
.maybank2u.com.sg
.ocbc.com
.posb.com.sg
.sgx.com
.singlife.com
.syfe.com
.trustbank.sg
.uob.com.sg

# Longbridge Singapore

.longbridge.sg

# ============================================================
# Futu / Moomoo Singapore
# ============================================================

.futusg.com
.moomootrustee.com

# ============================================================
# Interactive Brokers Singapore
# ============================================================

.ibkr.com.sg
.interactivebrokers.com.sg

# ============================================================
# uSMART Singapore
# ============================================================

.usmart.sg

# ============================================================
# Webull Singapore
# ============================================================

.webull.com.sg
