# United Kingdom financial services
.barclays.co.uk
.chase.co.uk
.firstdirect.com
.halifax.co.uk
.hsbc.co.uk
.lloydsbank.com
.monzo.com
.nationwide.co.uk
.natwest.com
.rbs.co.uk
.santander.co.uk
.starlingbank.com
.tsb.co.uk
.virginmoney.com
