# United Kingdom financial services
.atombank.co.uk
.bankofscotland.co.uk
.barclays.co.uk
.chase.co.uk
.co-operativebank.co.uk
.firstdirect.com
.halifax.co.uk
.hsbc.co.uk
.lloydsbank.com
.metrobankonline.co.uk
.monzo.com
.nationwide.co.uk
.natwest.com
.rbs.co.uk
.santander.co.uk
.starlingbank.com
.tsb.co.uk
.virginmoney.com
