#!/usr/bin/env python3
"""Render a copy-ready, fully expanded Surge [Rule] section."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Sequence


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]


def load_configuration(root: Path) -> tuple[Path, Path, str, list[dict[str, str]]]:
    manifest_path = root / "rules-manifest.json"
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    source = root / data["main"]
    output = root / data.get("expanded", "surge-expanded.conf")
    raw_base = (
        "https://raw.githubusercontent.com/"
        f"{data['repository']}/{data['branch']}/"
    )
    return source, output, raw_base, data["active"]


def read_domain_entries(path: Path) -> list[str]:
    return [
        line
        for line in path.read_text(encoding="utf-8").splitlines()
        if line and not line.startswith("#")
    ]


def render_expanded(root: Path = REPOSITORY_ROOT) -> str:
    source, _, raw_base, bindings = load_configuration(root)
    binding_by_url = {
        f"{raw_base}{binding['file']}": binding for binding in bindings
    }
    output: list[str] = []
    injected = 0

    for raw_line in source.read_text(encoding="utf-8").splitlines():
        fields = [field.strip() for field in raw_line.split(",")]
        if len(fields) >= 3 and fields[0] == "DOMAIN-SET":
            binding = binding_by_url.get(fields[1])
        else:
            binding = None

        if binding is None:
            output.append(raw_line)
            continue

        file_name = binding["file"]
        policy = binding["policy"]
        entries = read_domain_entries(root / file_name)
        output.append(f"# BEGIN {file_name} -> {policy}")
        for entry in entries:
            if entry.startswith("."):
                rule_type = "DOMAIN-SUFFIX"
                domain = entry[1:]
            else:
                rule_type = "DOMAIN"
                domain = entry
            output.append(
                f"{rule_type},{domain},{policy},extended-matching"
            )
            injected += 1
        output.append(f"# END {file_name} ({len(entries)} entries)")

    output.insert(
        1,
        (
            "# AUTO-GENERATED by scripts/build_expanded.py; "
            f"{injected} DOMAIN-SET entries expanded inline."
        ),
    )
    output.insert(
        2,
        "# Do not edit this file directly; edit the source DOMAIN-SET files.",
    )
    return "\n".join(output) + "\n"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=REPOSITORY_ROOT,
        help="repository root",
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="write the expanded file")
    mode.add_argument(
        "--check",
        action="store_true",
        help="fail when the committed expanded file is stale",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    root = args.root.resolve()
    _, output, _, _ = load_configuration(root)
    rendered = render_expanded(root)
    if args.write:
        output.write_text(rendered, encoding="utf-8")
        print(f"Wrote {output} ({len(rendered.splitlines())} lines)")
        return 0

    try:
        committed = output.read_text(encoding="utf-8")
    except OSError as exc:
        print(f"cannot read expanded file: {exc}", file=sys.stderr)
        return 1
    if committed != rendered:
        print(
            f"{output} is stale; run scripts/build_expanded.py --write",
            file=sys.stderr,
        )
        return 1
    print(f"{output} is up to date ({len(rendered.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
