#!/usr/bin/env python3
"""Render a copy-ready, fully expanded Surge [Rule] section."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Sequence


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
LOCAL_RULE_OPTIONS = {"extended-matching", "no-resolve"}


def load_configuration(root: Path) -> tuple[Path, Path, str, list[dict[str, str]]]:
    manifest_path = root / "rules-manifest.json"
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    source = root / data["main"]
    output = root / data.get("expanded", "surge-expanded.conf")
    raw_base = (
        "https://raw.githubusercontent.com/"
        f"{data['repository']}/{data['branch']}/"
    )
    return source, output, raw_base, data["active"]


def read_domain_entries(path: Path) -> list[str]:
    return [
        line
        for line in path.read_text(encoding="utf-8").splitlines()
        if line and not line.startswith("#")
    ]


def read_rule_entries(path: Path) -> list[str]:
    return read_domain_entries(path)


def split_rule_fields(raw: str) -> list[str]:
    """Split policy-free rules without splitting nested logical matchers."""
    fields: list[str] = []
    start = 0
    depth = 0
    for index, character in enumerate(raw):
        if character == "(":
            depth += 1
        elif character == ")":
            depth -= 1
        elif character == "," and depth == 0:
            fields.append(raw[start:index].strip())
            start = index + 1
    fields.append(raw[start:].strip())
    return fields


def expand_rule_set_entry(
    entry: str,
    policy: str,
) -> str:
    fields = split_rule_fields(entry)
    local_options: list[str] = []
    while len(fields) > 2 and fields[-1].casefold() in LOCAL_RULE_OPTIONS:
        local_options.insert(0, fields.pop())

    options: list[str] = []
    seen_options: set[str] = set()
    for option in local_options:
        normalized = option.casefold()
        if normalized in seen_options:
            continue
        seen_options.add(normalized)
        options.append(option)
    return ",".join((*fields, policy, *options))


def render_expanded(root: Path = REPOSITORY_ROOT) -> str:
    source, _, raw_base, bindings = load_configuration(root)
    binding_by_url = {
        f"{raw_base}{binding['file']}": binding for binding in bindings
    }
    output: list[str] = []
    injected = 0
    binding_types = {
        binding.get("type", "DOMAIN-SET") for binding in bindings
    }

    for raw_line in source.read_text(encoding="utf-8").splitlines():
        fields = [field.strip() for field in raw_line.split(",")]
        if len(fields) >= 3 and fields[0] in {"DOMAIN-SET", "RULE-SET"}:
            binding = binding_by_url.get(fields[1])
            if binding is not None and fields[0] != binding.get(
                "type", "DOMAIN-SET"
            ):
                binding = None
        else:
            binding = None

        if binding is None:
            output.append(raw_line)
            continue

        file_name = binding["file"]
        policy = binding["policy"]
        binding_type = binding.get("type", "DOMAIN-SET")
        if binding_type == "RULE-SET" and fields[3:]:
            raise ValueError(
                f"{file_name} must not use outer RULE-SET options"
            )
        entries = read_rule_entries(root / file_name)
        output.append(f"# BEGIN {file_name} -> {policy}")
        for entry in entries:
            if binding_type == "DOMAIN-SET":
                if entry.startswith("."):
                    rule_type = "DOMAIN-SUFFIX"
                    domain = entry[1:]
                else:
                    rule_type = "DOMAIN"
                    domain = entry
                output.append(
                    f"{rule_type},{domain},{policy},extended-matching"
                )
            else:
                output.append(
                    expand_rule_set_entry(entry, policy)
                )
            injected += 1
        output.append(f"# END {file_name} ({len(entries)} entries)")

    if binding_types == {"DOMAIN-SET"}:
        generated_description = (
            "# AUTO-GENERATED by scripts/build_expanded.py; "
            f"{injected} DOMAIN-SET entries expanded inline."
        )
        source_description = (
            "# Do not edit this file directly; edit the source DOMAIN-SET files."
        )
    else:
        generated_description = (
            "# AUTO-GENERATED by scripts/build_expanded.py; "
            f"{injected} local rule entries expanded inline."
        )
        source_description = (
            "# Do not edit this file directly; edit the source local rule files."
        )
    output.insert(1, generated_description)
    output.insert(2, source_description)
    return "\n".join(output) + "\n"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=REPOSITORY_ROOT,
        help="repository root",
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="write the expanded file")
    mode.add_argument(
        "--check",
        action="store_true",
        help="fail when the committed expanded file is stale",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    root = args.root.resolve()
    _, output, _, _ = load_configuration(root)
    rendered = render_expanded(root)
    if args.write:
        output.write_text(rendered, encoding="utf-8")
        print(f"Wrote {output} ({len(rendered.splitlines())} lines)")
        return 0

    try:
        committed = output.read_text(encoding="utf-8")
    except OSError as exc:
        print(f"cannot read expanded file: {exc}", file=sys.stderr)
        return 1
    if committed != rendered:
        print(
            f"{output} is stale; run scripts/build_expanded.py --write",
            file=sys.stderr,
        )
        return 1
    print(f"{output} is up to date ({len(rendered.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
